#!/usr/bin/env ruby

require 'qwtf_discord_bot'
require 'thor'

class QwtfDiscordBotExe < Thor
  def self.exit_on_failure?
    true
  end

  desc 'server', 'Responds to `!server` with server information'
  method_option :endpoints, type: :array, alias: '-e', default: ['localhost:27500']
  def server
    server_bot = QwtfDiscordBotServer.new(options[:endpoints])
    server_bot.run
  end

  desc 'watcher', 'Watches server and accounces when a player joins'
  method_option :endpoints, type: :array, alias: '-e', default: ['localhost:27500']
  def watcher
    watcher_bot = QwtfDiscordBotWatcher.new(options[:endpoints])
    watcher_bot.run
  end
end

QwtfDiscordBotExe.start
