#!/usr/bin/env ruby

require 'qwtf_discord_bot'
require 'thor'

class QwtfDiscordBotExe < Thor
  def self.exit_on_failure?
    true
  end

  desc 'server', 'Responds to user commands with server information'
  def server
    server_bot = QwtfDiscordBotServer.new
    server_bot.run
  end

  desc 'pug', 'Start, join, leave, record pick-up games.'
  def pug
    pub_bot = QwtfDiscordBotPug.new
    pug_bot.run
  end

  desc 'watcher', 'Watches servers and accounces when a player joins'
  def watcher
    watcher_bot = QwtfDiscordBotWatcher.new
    watcher_bot.run
  end
end

QwtfDiscordBotExe.start
