#!/usr/bin/env ruby

require 'qwtf_discord_bot'
require 'thor'

class QwtfDiscordBotExe < Thor
  def self.exit_on_failure?
    true
  end

  desc 'server', 'Responds to `!server` with server information'
  method_option :hostname, alias: '-h', default: 'localhost'
  method_option :port, type: :numeric, alias: '-p', default: 27500
  def server
    hostname = options['hostname']
    port = options['port']
    server_bot = QwtfDiscordBotServer.new(hostname: hostname, port: port)
    server_bot.run
  end

  desc 'watcher', 'Watches server and accounces when a player joins'
  method_option :hostname, alias: '-h', default: 'localhost'
  method_option :port, type: :numeric, alias: '-p', default: 27500
  def watcher
    hostname = options['hostname']
    port = options['port']
    watcher_bot = QwtfDiscordBotWatcher.new(hostname: hostname, port: port)
    watcher_bot.run
  end
end

QwtfDiscordBotExe.start
